### PR TITLE
update fbjs dependency

### PR DESCRIPTION
**Pull request by khakulov**

### CODE REVIEW

**Comment by felixgirault** [comment]
Thank you :)

**Comment by seansfkelley** [comment]
Hey, fwiw, I actually did this on purpose: https://github.com/felixgirault/pure-render-decorator/pull/3/commits/be64728d224b0b16d633e1eb98d6cb9f71c7c1ec

Why do you need to update it? Did they actually change how shallow compare works?

**Comment by felixgirault** [comment]
Thank you for noticing.
I merged this request because I thought it was a typo, it seemed natural to me that we would want potential bugfixes. Do you really think they could break shallow compare so easily?

@khakulov did you know about that or did you also think it was a typo?

**Comment by seansfkelley** [comment]
It seems pretty unlikely to be honest, but I just figured why not, better safe than sorry.

**Comment by khakulov** [comment]
I had a version conflict in my project with other dependencies, so that fbjs functions compiled double in my bundle. In other side, if fbjs so unstable, why are you using it? Maybe just copy the shallowEqual function?

**Comment by felixgirault** [comment]
I think we can leave it as is.
Maybe they can break small features here and there, but it seems really unlikely that they could break `shallowCompare()`, given that it is widely used, and has a small and well defined purpose.

**Pull request merged**
